### ISSUE TITLE
gulp issue on npm install

### ISSUE THREAD

**Issue by magland** [NeurophysVis/RasterVis#38]
@edeno I am getting this error on `npm install`. I am using Ubuntu

```
> rastervis@0.0.1 postinstall
> bower cache clean && bower install && gulp

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/home/magland/src/RasterVis/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/home/magland/src/RasterVis/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/home/magland/src/RasterVis/gulpfile.js:142:6)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at requireOrImport (/home/magland/src/RasterVis/node_modules/gulp-cli/lib/shared/require-or-import.js:19:11) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
npm ERR! code 1
npm ERR! path /home/magland/src/RasterVis
npm ERR! command failed
npm ERR! command sh -c bower cache clean && bower install && gulp
```

**Comment by edeno** [comment]
Ah hm. This seems to be a gulp3 vs gulp4 issue. I'm investigating on how to fix.

**Comment by magland** [comment]
Yeah. I replaced

```
gulp.task('default', ['copyDATA', 'bundle', 'createVendorJS', 'copyCSS', 'webserver', 'watch']);
gulp.task('build', ['createMainJS', 'createMainJS', 'createVendorJS', 'copyCSS', 'createMainJS-build', 'createVendorJS-build', 'minifyCSS', 'compressImages', 'minifyJSON']);
```

by

```
gulp.task('default', gulp.series('copyDATA', 'bundle', 'createVendorJS', 'copyCSS', 'webserver', 'watch'));
gulp.task('build', gulp.series('createMainJS', 'createMainJS', 'createVendorJS', 'copyCSS', 'createMainJS-build', 'createVendorJS-build', 'minifyCSS', /*'compressImages', */'minifyJSON'));
```

Notice I needed to comment out compressImages because that wasn't defined.

But now I am getting:

```
[11:43:58] Using gulpfile ~/src/RasterVis/gulpfile.js
[11:43:58] Starting 'default'...
[11:43:58] Starting 'copyDATA'...
[11:43:58] Finished 'copyDATA' after 11 ms
[11:43:58] Starting 'bundle'...
[11:43:58] The following tasks did not complete: default, bundle
[11:43:58] Did you forget to signal async completion?
```

**Comment by edeno** [comment]
I pushed a fix (I think). Could you try that?

**Comment by magland** [comment]
Now I'm getting

```
> bower cache clean && bower install && gulp

[12:09:42] Using gulpfile ~/src/RasterVis/gulpfile.js
[12:09:42] Starting 'default'...
[12:09:42] Starting 'copyDATA'...
[12:09:42] Finished 'copyDATA' after 6.28 ms
[12:09:42] Starting 'bundle'...
[12:09:42] 'bundle' errored after 15 ms
[12:09:42] Error in plugin 'gulp-rollup'
Message:
    Unexpected key 'name' found, expected one of: banner, dest, entry, exports, external, footer, format, globals, indent, intro, moduleId, moduleName, noConflict, onwarn, outro, plugins, preferConst, sourceMap, treeshake, useStrict
Details:
    domainEmitter: [object Object]
    domainThrown: false
[12:09:42] 'default' errored after 23 ms
npm ERR! code 1
npm ERR! path /home/magland/src/RasterVis
npm ERR! command failed
npm ERR! command sh -c bower cache clean && bower install && gulp

npm ERR! A complete log of this run can be found in: /home/magland/.npm/_logs/2024-02-21T17_09_35_168Z-debug-0.log
```

**Comment by edeno** [comment]
Err okay, I guess I shouldn't have changed the key names. I reverted the key names back.

**Comment by magland** [comment]
Looks like progress. Now I am getting

```bash
$ npm install

> rastervis@0.0.1 postinstall
> bower cache clean && bower install && gulp

[12:33:59] Using gulpfile ~/src/RasterVis/gulpfile.js
[12:33:59] Starting 'default'...
[12:33:59] Starting 'copyDATA'...
[12:33:59] Finished 'copyDATA' after 11 ms
[12:33:59] Starting 'bundle'...
[12:33:59] Finished 'bundle' after 127 ms
[12:33:59] Starting 'createVendorJS'...
[12:33:59] 'createVendorJS' errored after 4.96 ms
[12:33:59] Error: File not found with singular glob: /home/magland/src/RasterVis/app/components/queue-async/queue.js (if this was purposeful, use `allowEmpty` option)
    at Glob.<anonymous> (/home/magland/src/RasterVis/node_modules/glob-stream/readable.js:84:17)
    at Object.onceWrapper (node:events:629:26)
    at Glob.emit (node:events:514:28)
    at Glob.emit (node:domain:488:12)
    at Glob._finish (/home/magland/src/RasterVis/node_modules/glob/glob.js:194:8)
    at done (/home/magland/src/RasterVis/node_modules/glob/glob.js:179:14)
    at Glob._processSimple2 (/home/magland/src/RasterVis/node_modules/glob/glob.js:688:12)
    at /home/magland/src/RasterVis/node_modules/glob/glob.js:676:10
    at Glob._stat2 (/home/magland/src/RasterVis/node_modules/glob/glob.js:772:12)
    at lstatcb_ (/home/magland/src/RasterVis/node_modules/glob/glob.js:764:12)
[12:33:59] 'default' errored after 145 ms
npm ERR! code 1
npm ERR! path /home/magland/src/RasterVis
npm ERR! command failed
npm ERR! command sh -c bower cache clean && bower install && gulp

npm ERR! A complete log of this run can be found in: /home/magland/.npm/_logs/2024-02-21T17_33_51_768Z-debug-0.log
```

**Comment by edeno** [comment]
Awesome. Thank you for your help debugging that. I will push those changes.

Most of this was put together 6 years ago so I'm impressed that it could still work this quickly hah.
